version: '3.3'

services:
  db:
    image: mysql
    secrets:
      - root_db_password
      - wordpress_db_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_db_password
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /opt/docker/volumes/mysql
        target: /var/lib/mysql
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    secrets:
      - wordpress_db_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
       - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  adminer:
    image: adminer
    ports:
      - 8001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

secrets:
  root_db_password:
    external: true
  wordpress_db_password:
    external: true

networks:
  appnet:
    external: true
