version: "3.3"

services:
  registry:
    image: registry:2
    networks:
      - appnet
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: /mnt/volumes/registry/data
        target: /var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  appnet:
    external: true
