version: '3.4'

services:
  mediawiki:
    image: mediawiki
    networks:
      - appnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.backend.loadbalancer.sticky=false"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=mediawiki"
        - "traefik.docker.network=appnet"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:mediawiki.domain.com"
        - "traefik.port=80"
    environment:
      - MEDIAWIKI_SERVER=http://localhost:80
      - MEDIAWIKI_SITENAME=MyWiki
      - MEDIAWIKI_LANGUAGE_CODE=en
      - MEDIAWIKI_SECRET_KEY=mysecret
      - MEDIAWIKI_DB_TYPE=sqlite
      - MEDIAWIKI_DB_NAME=wikidb
      - MEDIAWIKI_ENABLE_UPLOADS=1
      - MEDIAWIKI_EXTENSION_VISUAL_EDITOR_ENABLED=1
      - MEDIAWIKI_DEFAULT_SKIN=vector
      - MEDIAWIKI_DEBUG=1

networks:
  appnet:
    external: true
