version: '3'

services:
  web:
    image: rbekker87/flask-redis:alpine
    networks:
      - appnet
    ports:
      - 8000:5000
    deploy:
      replicas: 10
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
        
  redis:
    image: redis:alpine
    
networks:
  appnet:
    external: true
