version: "3.3"

services:
  mongodb:
    image: tutum/mongodb:latest
    networks:
      - appnet
    volumes:
      - type: bind
        source: /mnt/volumes/mongodb/data
        target: /var/www/ghost/content/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock     
    environment:
      - MONGODB_USER=admin
      - MONGODB_PASS=password
      - MONGODB_DATABASE=mydb
      - OPLOG_SIZE=50
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
networks:
  appnet:
    external: true
