version: "3.2"

services:
  whoami:
    image: rbekker87/golang-whoami:latest
    networks:
      - appnet
      - traefik
    deploy:
      mode: replicated
      replicas: 10
      labels:
        - "traefik.backend=whoami"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:whoami.mydomain.com"
        - "traefik.docker.network=traefik"
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.10'
          memory: 32M

networks:
  appnet:
  traefik
    external: true
