version: '3.3'

services:
  nginx_proxy:
    image: registry.gitlab.com/<user>/<repo>/proxy-nginx:<tag>
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

networks:
  appnet:
    external: true
