version: "3.3"

services:
  rocketchat:
    image: rocketchat/rocket.chat
    environment:
      - DEPLOY_METHOD=docker 
      - NODE_ENV=production 
      - PORT=3000 
      - MONGO_URL=mongodb://username:password@mongodb.domain.com:27017/rocketchat 
      - ROOT_URL=https://rocketchat.domain.com
      - ADMIN_USERNAME=superadmin
      - ADMIN_PASS=supersecret
      - ADMIN_EMAIL=email@domain.com 
      - Accounts_AvatarStorePath=/app/uploads    
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1

networks:
  appnet:
    external: true
