version: "3.2"

services:
  proxy:
    image: <user>/<repo>:<tag>
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1
      
  scooby:
    image: rbekker87/golang-whoami:latest
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1

  travis:
    image: rbekker87/golang-whoami:latest
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1

  zazu:
    image: rbekker87/golang-whoami:latest
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1


networks:
  appnet:
    external: true
