version: "3.3"

services:
  minio:
    image: minio/minio
    command: server /data
    networks:
      - appnet
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=AKIAASDKJASDL
      - MINIO_SECRET_KEY=AKIAASDKJASDL
    volumes:
      - type: bind
        source: /gluster/bricks/1/minio
        target: /data
    deploy:
      mode: replicated
      replicas: 1

networks:
  appnet:
    external: true
