version: '3'

services:
  console:
    image: {registry}/{user}/{repo}/{image}:{tag}
    networks:
      - appnet
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=appnet"
        - "traefik.frontend.rule=Host:apps.domain.com; PathPrefix: /web/"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'
      resources:
        limits:
          cpus: '0.01'
          memory: 256M
        reservations:
          cpus: '0.001'
          memory: 128M

networks:
  appnet:
    external: true
