version: '3'

services:
  traefik:
    image: hypriot/rpi-traefik
    command: --web --docker --docker.swarmmode --logLevel=DEBUG
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  appnet:
    external: true
