version: "3.3"

services:
  minio:
    image: dockersamples/visualizer:stable
    networks:
      - appnet
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  appnet:
    external: true
